application: mitomotif
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /stylesheets/main.css
  static_files: static/stylesheets/main.css
  upload: static/images/main.css

- url: .*
  script: main.py

