application: mitomotif
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /stylesheets
  static_files: static/stylesheets
  upload: static/images/*.css

- url: .*
  script: main.py

